// <auto-generated />
namespace WebTimer.ServiceHost.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Analytics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Analytics));
        
        string IMigrationMetadata.Id
        {
            get { return "201311060235242_Analytics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
